services:
  mssql:
    container_name: mssql-server
    build: "./mssql-server"
    ports:
      - "1433:1433"
    volumes:
      - ./mssql-server/backup:/home/mssql/backup
    networks:
      mssql-php:
        ipv4_address: 172.19.0.22
  php:
    container_name: php
    image: namoshek/php-mssql:8.3-fpm-alpine
    volumes:
      - ./import:/home/import
    ports:
      - "8080:80"
    networks:
      - mssql-php

networks:
  mssql-php:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16